import Head from 'next/head'
import Image from 'next/image'

import Homepage from '../components/Homepage'
import Prayerbox from '../components/Prayerbox'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-[#D4D4D4]" >
        <Homepage/>
        <Prayerbox/>
      </div>

     
    </div>
  )
}
